const warWeightData = {
  TH12: [
    { name: 'Town Hall Giga Tesla', level: 5 },
    { name: 'Eagle Artillery', level: 3 },
    { name: 'Inferno Tower', index: 1, level: 6 },
    { name: 'Inferno Tower', index: 2, level: 6 },
    { name: 'Inferno Tower', index: 3, level: 6 },
    { name: 'X-Bow', index: 1, level: 6 },
    { name: 'X-Bow', index: 2, level: 6 },
    { name: 'X-Bow', index: 3, level: 6 },
    { name: 'X-Bow', index: 4, level: 6 },
  ],

  TH13: [
    { name: 'Scattershot', index: 1, builtLevel: 1 },
    { name: 'Scattershot', index: 2, builtLevel: 1 },
    { name: 'Scattershot', index: 1, level: 2, requiresBuiltLevel1: true },
    { name: 'Scattershot', index: 2, level: 2, requiresBuiltLevel1: true },
    { name: 'Eagle Artillery', level: 4 },
    { name: 'Town Hall Giga Inferno', level: 5 },
    { name: 'Inferno Tower', index: 1, level: 7 },
    { name: 'Inferno Tower', index: 2, level: 7 },
    { name: 'Inferno Tower', index: 3, level: 7 },
    { name: 'X-Bow', index: 1, level: 8 },
    { name: 'X-Bow', index: 2, level: 8 },
    { name: 'X-Bow', index: 3, level: 8 },
    { name: 'X-Bow', index: 4, level: 8 },
  ],

  TH14: [
    { name: 'Builder Hut', index: 1, builtLevel: 1 },
    { name: 'Builder Hut', index: 2, builtLevel: 1 },
    { name: 'Builder Hut', index: 3, builtLevel: 1 },
    { name: 'Builder Hut', index: 4, builtLevel: 1 },
    { name: 'Builder Hut', index: 5, builtLevel: 1 },
    { name: 'Builder Hut', index: 1, level: 4, requiresBuiltLevel1: true },
    { name: 'Builder Hut', index: 2, level: 4, requiresBuiltLevel1: true },
    { name: 'Builder Hut', index: 3, level: 4, requiresBuiltLevel1: true },
    { name: 'Builder Hut', index: 4, level: 4, requiresBuiltLevel1: true },
    { name: 'Builder Hut', index: 5, level: 4, requiresBuiltLevel1: true },
    { name: 'Scattershot', index: 1, level: 3, requiresBuiltLevel1: true },
    { name: 'Scattershot', index: 2, level: 3, requiresBuiltLevel1: true },
    { name: 'Eagle Artillery', level: 5 },
    { name: 'Town Hall Giga Inferno', level: 5 },
    { name: 'Inferno Tower', index: 1, level: 8 },
    { name: 'Inferno Tower', index: 2, level: 8 },
    { name: 'Inferno Tower', index: 3, level: 8 },
    { name: 'X-Bow', index: 1, level: 9 },
    { name: 'X-Bow', index: 2, level: 9 },
    { name: 'X-Bow', index: 3, level: 9 },
    { name: 'X-Bow', index: 4, level: 9 },
  ],

  TH15: [
    { name: 'Monolith', builtLevel: 1 },
    { name: 'Spell Tower', index: 1, builtLevel: 1 },
    { name: 'Spell Tower', index: 2, builtLevel: 1 },
    { name: 'Monolith', level: 2, requiresBuiltLevel1: true },
    { name: 'Spell Tower', index: 1, level: 3, requiresBuiltLevel1: true },
    { name: 'Spell Tower', index: 2, level: 3, requiresBuiltLevel1: true },
    { name: 'Scattershot', index: 1, level: 4 },
    { name: 'Scattershot', index: 2, level: 4 },
    { name: 'Eagle Artillery', level: 6 },
    { name: 'Town Hall Giga Inferno', level: 5 },
    { name: 'Inferno Tower', index: 1, level: 9 },
    { name: 'Inferno Tower', index: 2, level: 9 },
    { name: 'Inferno Tower', index: 3, level: 9 },
    { name: 'X-Bow', index: 1, level: 10 },
    { name: 'X-Bow', index: 2, level: 10 },
    { name: 'X-Bow', index: 3, level: 10 },
    { name: 'X-Bow', index: 4, level: 10 },
  ],

  TH16: [
    { name: 'Ricochet Cannon', index: 1, builtLevel: 1, merged: true },
    { name: 'Ricochet Cannon', index: 2, builtLevel: 1, merged: true },
    { name: 'Multi Archer Tower', index: 1, builtLevel: 1, merged: true },
    { name: 'Multi Archer Tower', index: 2, builtLevel: 1, merged: true },
    { name: 'Ricochet Cannon', index: 1, level: 2, requiresBuiltLevel1: true },
    { name: 'Ricochet Cannon', index: 2, level: 2, requiresBuiltLevel1: true },
    { name: 'Multi Archer Tower', index: 1, level: 2, requiresBuiltLevel1: true },
    { name: 'Multi Archer Tower', index: 2, level: 2, requiresBuiltLevel1: true },
    { name: 'Monolith', level: 3 },
    { name: 'Scattershot', index: 1, level: 5 },
    { name: 'Scattershot', index: 2, level: 5 },
    { name: 'Inferno Tower', index: 1, level: 10 },
    { name: 'Inferno Tower', index: 2, level: 10 },
    { name: 'Inferno Tower', index: 3, level: 10 },
    { name: 'X-Bow', index: 1, level: 11 },
    { name: 'X-Bow', index: 2, level: 11 },
    { name: 'X-Bow', index: 3, level: 11 },
    { name: 'X-Bow', index: 4, level: 11 },
    { name: 'Builder Hut', index: 1, level: 6 },
    { name: 'Builder Hut', index: 2, level: 6 },
    { name: 'Builder Hut', index: 3, level: 6 },
    { name: 'Builder Hut', index: 4, level: 6 },
    { name: 'Builder Hut', index: 5, level: 6 },
    { name: 'Wizard Tower', index: 1, level: 16 },
    { name: 'Wizard Tower', index: 2, level: 16 },
    { name: 'Wizard Tower', index: 3, level: 16 },
    { name: 'Wizard Tower', index: 4, level: 16 },
    { name: 'Wizard Tower', index: 5, level: 16 },
  ],

  TH17: [
    { name: 'Multi-Gear Tower', builtLevel: 1, merged: true },
    { name: 'Fire Spitter', index: 1, builtLevel: 1 },
    { name: 'Fire Spitter', index: 2, builtLevel: 1 },
    { name: 'Ricochet Cannon', index: 3, builtLevel: 1, merged: true },
    { name: 'Multi Archer Tower', index: 3, builtLevel: 1, merged: true },
    { name: 'Multi-Gear Tower', level: 2, requiresBuiltLevel1: true },
    { name: 'Fire Spitter', index: 1, level: 2, requiresBuiltLevel1: true },
    { name: 'Fire Spitter', index: 2, level: 2, requiresBuiltLevel1: true },
    { name: 'Ricochet Cannon', index: 1, level: 3, merged: true },
    { name: 'Ricochet Cannon', index: 2, level: 3, merged: true },
    { name: 'Ricochet Cannon', index: 3, level: 3, requiresBuiltLevel1: true, merged: true },
    { name: 'Multi Archer Tower', index: 1, level: 3, merged: true },
    { name: 'Multi Archer Tower', index: 2, level: 3, merged: true },
    { name: 'Multi Archer Tower', index: 3, level: 3, requiresBuiltLevel1: true, merged: true },
    { name: 'Town Hall Inferno Artillery', level: 5 },
    { name: 'Monolith', level: 4 },
    { name: 'Scattershot', index: 1, level: 6 },
    { name: 'Scattershot', index: 2, level: 6 },
    { name: 'Inferno Tower', index: 1, level: 11 },
    { name: 'Inferno Tower', index: 2, level: 11 },
    { name: 'Inferno Tower', index: 3, level: 11 },
    { name: 'X-Bow', index: 1, level: 12 },
    { name: 'X-Bow', index: 2, level: 12 },
    { name: 'X-Bow', index: 3, level: 12 },
    { name: 'X-Bow', index: 4, level: 12 },
    { name: 'Builder Hut', index: 1, level: 7 },
    { name: 'Builder Hut', index: 2, level: 7 },
    { name: 'Builder Hut', index: 3, level: 7 },
    { name: 'Builder Hut', index: 4, level: 7 },
    { name: 'Builder Hut', index: 5, level: 7 },
    { name: 'Wizard Tower', index: 1, level: 17 },
    { name: 'Wizard Tower', index: 2, level: 17 },
    { name: 'Wizard Tower', index: 3, level: 17 },
    { name: 'Wizard Tower', index: 4, level: 17 },
    { name: 'Wizard Tower', index: 5, level: 17 },
  ],
};
